# Config for SDF Utils

# Relation types:
# member, ally, truce, neutral, enemy, wilderness, warzone, safezone
# Faction-less people to neutral to Player factions.

restrictions:
  noTP:
    enabled: true
    bypassPerm: 'spacedelta.staff'
    # Which relations will be affected by this restriction.
    relations:
      - enemy
      - truce
      - ally
      - neutral
    denyMessage: '&eSorry, you cannot TP there! That is another faction''s land.'
  noHome:
    enabled: true
    bypassPerm: 'spacedelta.staff'
    relations:
      - enemy
      - truce
      - ally
      - neutral
      - warzone
    denyMessage: '&eSorry, you cannot set a home here!'
    # Unique settings to this restriction.
    unique:
      # Checks through homes of a user and deletes the homes which violate this restriction.
      deleteViolatingHomes: true
      deletedViolatedHomesMessage: '&cSome of your homes (%deletedHomes%) were automatically deleted for being in another faction''s territory.'
      # Commands to block in this setting. Will also block "plugin:command" style commands.
      # Please keep lower-case.
      blockedCommands:
        - 'sethome'
        - 'esethome'
        - 'createhome'
        - 'ecreatehome'
  noLogout:
    enabled: true
    bypassPerm: 'spacedelta.staff'
    # Which relations will be affected by this restriction.
    relations:
      - enemy
      - truce
      - ally
      - neutral
    denyMessage: '&cYou were sent to spawn for being logged out in the enemy land.'
    unique:
      # The period when a player logs out, if they are in affected relation terrority, will they WON'T be sent back to spawn.
      # When the time ends and they have not reconnected, they go back to spawn.
      # (In seconds)
      logoutGracePeriod: 60
