name: SDFUtils
main: net.spacedelta.sdfutils.SDFUtils
version: 0.1-SNAPSHOT
author: Ellie#006
website: spacedelta.net
description: A plugin to catch, patch exploits and issues common within Factions.

depend: [SavageFactions]
softdepend: [Essentials]

commands:
  sdfutil:
    description: Main plugin command.
    permission: "sdfutil.reload"

permissions:
  sdfutil.reload:
    description: Permission to use the main command.
